local plugin = require("flutter-launch")

vim.api.nvim_create_user_command("FlutterAttach", function()
  plugin.attach()
end, {})
vim.api.nvim_create_user_command("FlutterHotReload", function()
  plugin.sendCommand("r")
end, {})
vim.api.nvim_create_user_command("FlutterHotRestart", function()
  plugin.sendCommand("R")
end, {})
vim.api.nvim_create_user_command("FlutterDetach", function()
  plugin.terminateJob()
end, {})
vim.api.nvim_create_user_command("FlutterInfoToggle", function()
  plugin.toggleInfoBuffer()
end, {})

